import "./globals.css";
import { sora } from "./fonts";

export const metadata = {
  title: "Skillphore",
  description:
    "Skillphore fosters a supportive data analytics community, boosting confidence and practical skills through real-world projects, courses and mentorship, leading to successful career transitions.Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>{children}</body>
      <Script id="fb_pixel">
        {`!function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '870814621343514');
        fbq('track', 'PageView');`}
      </Script>

      <noscript>
        <img
          height="1"
          width="1"
          style="display:none"
          src="https://www.facebook.com/tr?id=870814621343514&ev=PageView&noscript=1"
        />
      </noscript>
    </html>
  );
}
